[package]
name = "FOMOSv1-Yellow"
version = "1.5.3"
edition = "2018"

[[bin]]
name = "FOMSOv1-Yellow"
edition = "2018"
path = "src/main.rs"

[workspace]
members = [
    "apps/",
]

[dependencies]
apps = { path = "apps/" }
fk_std = "0.2.3"
gtk = "0.9.2"
gio = "0.9.1"
serde_json = "1.0.60"