all: editFile.c FMOE.c help.c makeFile.c openFile.c
	gcc -Wall editFile.c -o editFile
	gcc -Wall FMOE.c -o FMOE
	gcc -Wall help.c -o help
	gcc -Wall makeFile.c -o makeFile
	gcc -Wall openFile.c -o openFile

clean:
	@rm -rf editFile
	@rm -rf FMOE
	@rm -rf help
	@rm -rf makeFile
	@rm -rf openFile
